mesh_files:
  # TODO: Update package/path to point at cs66a meshes once available
  base:
    visual:
      mesh:
        package: eli_cs_robot_description
        path: meshes/cs66a/visual/base.dae
      material:
        name: "LightGrey"
        color: "0.35 0.7 1.0 1.0"
    collision:
      mesh:
        package: eli_cs_robot_description
        path: meshes/cs66a/collision/base.stl

  shoulder:
    visual:
      mesh:
        package: eli_cs_robot_description
        path: meshes/cs66a/visual/shoulder.dae
      material:
        name: "LightGrey"
        color: "0.35 0.7 1.0 1.0"
    collision:
      mesh:
        package: eli_cs_robot_description
        path: meshes/cs66a/collision/shoulder.stl

  upperarm:
    visual:
      mesh:
        package: eli_cs_robot_description
        path: meshes/cs66a/visual/upperarm.dae
      material:
        name: "LightGrey"
        color: "0.35 0.7 1.0 1.0"
    collision:
      mesh:
        package: eli_cs_robot_description
        path: meshes/cs66a/collision/upperarm.stl

  forearm:
    visual:
      mesh:
        package: eli_cs_robot_description
        path: meshes/cs66a/visual/forearm.dae
      material:
        name: "LightGrey"
        color: "0.35 0.7 1.0 1.0"
    collision:
      mesh:
        package: eli_cs_robot_description
        path: meshes/cs66a/collision/forearm.stl

  wrist_1:
    visual:
      mesh:
        package: eli_cs_robot_description
        path: meshes/cs66a/visual/wrist1.dae
      material:
        name: "LightGrey"
        color: "0.35 0.7 1.0 1.0"
    collision:
      mesh:
        package: eli_cs_robot_description
        path: meshes/cs66a/collision/wrist1.stl

  wrist_2:
    visual:
      mesh:
        package: eli_cs_robot_description
        path: meshes/cs66a/visual/wrist2.dae
      material:
        name: "LightGrey"
        color: "0.35 0.7 1.0 1.0"
    collision:
      mesh:
        package: eli_cs_robot_description
        path: meshes/cs66a/collision/wrist2.stl

  wrist_3:
    visual:
      mesh:
        package: eli_cs_robot_description
        path: meshes/cs66a/visual/wrist3.dae
      material:
        name: "LightGrey"
        color: "0.35 0.7 1.0 1.0"
    collision:
      mesh:
        package: eli_cs_robot_description
        path: meshes/cs66a/collision/wrist3.stl
